import { NgModule } from '@angular/core';

import {
  CompatibilityModule,
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatSidenavModule,
  MatSelectModule,
  MatDialogModule,
  MatSlideToggleModule,
  MatDatepickerModule,
  MatInputModule,
  MdInputModule,
  MatNativeDateModule,
  MatChipsModule,
  MatExpansionModule,
  MatGridListModule,
  MatFormFieldModule,
  MatStepperModule,
  MatRadioModule,
  MdTooltipModule,
  MdCheckboxModule
} from '@angular/material';

@NgModule({
  imports: [
    CompatibilityModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatSelectModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatDatepickerModule,
    MatInputModule,
    MatNativeDateModule,
    MatChipsModule,
    MatExpansionModule,
    MatGridListModule,
    MatFormFieldModule,
    MatStepperModule,
    MatRadioModule,
    MdInputModule,
    MdTooltipModule,
    MdCheckboxModule
  ],
  exports: [
    CompatibilityModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatSelectModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatDatepickerModule,
    MatInputModule,
    MatNativeDateModule,
    MatChipsModule,
    MatExpansionModule,
    MatGridListModule,
    MatFormFieldModule,
    MatStepperModule,
    MdInputModule,
    MatRadioModule,
    MdTooltipModule,
    MdCheckboxModule
  ]
})
export     class MaterialModule {}
